config/routes.rb
Zmd::Application.routes.draw do
  resources :splits

  resources :technicals

  resources :fundamentals

  resources :exchanges

  resources :eod_prices

  resources :asset_types

  resources :assets

end

app/models/fundamentals.rb
class Fundamentals < ActiveRecord::Base
  attr_accessible :asset_id, :sector, :industry, :pe, :eps, :div_yield, :shares, :dps, :peg, :p2s, :p2b
end

app/controllers/fundamentals_controller.rb
class FundamentalsController < ApplicationController
  def index
    @fundamentals = Fundamentals.all
  end
  
  def show
    @fundamentals = Fundamentals.find(params[:id])
  end
  
  def new
    @fundamentals = Fundamentals.new
  end
  
  def create
    @fundamentals = Fundamentals.new(params[:fundamentals])
    if @fundamentals.save
      flash[:notice] = "Successfully created fundamentals."
      redirect_to @fundamentals
    else
      render :action => 'new'
    end
  end
  
  def edit
    @fundamentals = Fundamentals.find(params[:id])
  end
  
  def update
    @fundamentals = Fundamentals.find(params[:id])
    if @fundamentals.update_attributes(params[:fundamentals])
      flash[:notice] = "Successfully updated fundamentals."
      redirect_to @fundamentals
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @fundamentals = Fundamentals.find(params[:id])
    @fundamentals.destroy
    flash[:notice] = "Successfully destroyed fundamentals."
    redirect_to fundamentals_url
  end
end

app/helpers/fundamentals_helper.rb
module FundamentalsHelper
end

app/views/fundamentals/_form.html.erb
<%= form_for @fundamentals do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :asset_id %><br />
    <%= f.text_field :asset_id %>
  </p>
  <p>
    <%= f.label :sector %><br />
    <%= f.text_field :sector %>
  </p>
  <p>
    <%= f.label :industry %><br />
    <%= f.text_field :industry %>
  </p>
  <p>
    <%= f.label :pe %><br />
    <%= f.text_field :pe %>
  </p>
  <p>
    <%= f.label :eps %><br />
    <%= f.text_field :eps %>
  </p>
  <p>
    <%= f.label :div_yield %><br />
    <%= f.text_field :div_yield %>
  </p>
  <p>
    <%= f.label :shares %><br />
    <%= f.text_field :shares %>
  </p>
  <p>
    <%= f.label :dps %><br />
    <%= f.text_field :dps %>
  </p>
  <p>
    <%= f.label :peg %><br />
    <%= f.text_field :peg %>
  </p>
  <p>
    <%= f.label :p2s %><br />
    <%= f.text_field :p2s %>
  </p>
  <p>
    <%= f.label :p2b %><br />
    <%= f.text_field :p2b %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/fundamentals/edit.html.erb
<% title "Edit Fundamentals" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @fundamentals %> |
  <%= link_to "View All", fundamentals_path %>
</p>

app/views/fundamentals/index.html.erb
<% title "Fundamentals" %>

<table>
  <tr>
    <th>Asset</th>
    <th>Sector</th>
    <th>Industry</th>
    <th>Pe</th>
    <th>Eps</th>
    <th>Div Yield</th>
    <th>Shares</th>
    <th>Dps</th>
    <th>Peg</th>
    <th>P2s</th>
    <th>P2b</th>
  </tr>
  <% for fundamentals in @fundamentals %>
    <tr>
      <td><%= fundamentals.asset_id %></td>
      <td><%= fundamentals.sector %></td>
      <td><%= fundamentals.industry %></td>
      <td><%= fundamentals.pe %></td>
      <td><%= fundamentals.eps %></td>
      <td><%= fundamentals.div_yield %></td>
      <td><%= fundamentals.shares %></td>
      <td><%= fundamentals.dps %></td>
      <td><%= fundamentals.peg %></td>
      <td><%= fundamentals.p2s %></td>
      <td><%= fundamentals.p2b %></td>
      <td><%= link_to "Show", fundamentals %></td>
      <td><%= link_to "Edit", edit_fundamentals_path(fundamentals) %></td>
      <td><%= link_to "Destroy", fundamentals, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Fundamentals", new_fundamentals_path %></p>

app/views/fundamentals/new.html.erb
<% title "New Fundamentals" %>

<%= render 'form' %>

<p><%= link_to "Back to List", fundamentals_path %></p>

app/views/fundamentals/show.html.erb
<% title "Fundamentals" %>

<p>
  <strong>Asset:</strong>
  <%= @fundamentals.asset_id %>
</p>
<p>
  <strong>Sector:</strong>
  <%= @fundamentals.sector %>
</p>
<p>
  <strong>Industry:</strong>
  <%= @fundamentals.industry %>
</p>
<p>
  <strong>Pe:</strong>
  <%= @fundamentals.pe %>
</p>
<p>
  <strong>Eps:</strong>
  <%= @fundamentals.eps %>
</p>
<p>
  <strong>Div Yield:</strong>
  <%= @fundamentals.div_yield %>
</p>
<p>
  <strong>Shares:</strong>
  <%= @fundamentals.shares %>
</p>
<p>
  <strong>Dps:</strong>
  <%= @fundamentals.dps %>
</p>
<p>
  <strong>Peg:</strong>
  <%= @fundamentals.peg %>
</p>
<p>
  <strong>P2s:</strong>
  <%= @fundamentals.p2s %>
</p>
<p>
  <strong>P2b:</strong>
  <%= @fundamentals.p2b %>
</p>

<p>
  <%= link_to "Edit", edit_fundamentals_path(@fundamentals) %> |
  <%= link_to "Destroy", @fundamentals, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", fundamentals_path %>
</p>