config/routes.rb
Zmd::Application.routes.draw do
  resources :splits

  resources :technicals

  resources :fundamentals

  resources :exchanges

  resources :eod_prices

  resources :asset_types

  resources :assets

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  attr_accessible :exchange_code, :symbol, :asset_type_id, :desc
end

app/models/asset_type.rb
class AssetType < ActiveRecord::Base
  attr_accessible :short_name, :long_name
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  def index
    @assets = Asset.all
  end
  
  def show
    @asset = Asset.find(params[:id])
  end
  
  def new
    @asset = Asset.new
  end
  
  def create
    @asset = Asset.new(params[:asset])
    if @asset.save
      flash[:notice] = "Successfully created asset."
      redirect_to @asset
    else
      render :action => 'new'
    end
  end
  
  def edit
    @asset = Asset.find(params[:id])
  end
  
  def update
    @asset = Asset.find(params[:id])
    if @asset.update_attributes(params[:asset])
      flash[:notice] = "Successfully updated asset."
      redirect_to @asset
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy
    flash[:notice] = "Successfully destroyed asset."
    redirect_to assets_url
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.erb
<%= form_for @asset do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :exchange_code %><br />
    <%= f.text_field :exchange_code %>
  </p>
  <p>
    <%= f.label :symbol %><br />
    <%= f.text_field :symbol %>
  </p>
  <p>
    <%= f.label :asset_type_id %><br />
    <%= f.text_field :asset_type_id %>
  </p>
  <p>
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/assets/edit.html.erb
<% title "Edit Asset" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @asset %> |
  <%= link_to "View All", assets_path %>
</p>

app/views/assets/index.html.erb
<% title "Assets" %>

<table>
  <tr>
    <th>Exchange Code</th>
    <th>Symbol</th>
    <th>Asset Type</th>
    <th>Desc</th>
  </tr>
  <% for asset in @assets %>
    <tr>
      <td><%= asset.exchange_code %></td>
      <td><%= asset.symbol %></td>
      <td><%= asset.asset_type_id %></td>
      <td><%= asset.desc %></td>
      <td><%= link_to "Show", asset %></td>
      <td><%= link_to "Edit", edit_asset_path(asset) %></td>
      <td><%= link_to "Destroy", asset, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Asset", new_asset_path %></p>

app/views/assets/new.html.erb
<% title "New Asset" %>

<%= render 'form' %>

<p><%= link_to "Back to List", assets_path %></p>

app/views/assets/show.html.erb
<% title "Asset" %>

<p>
  <strong>Exchange Code:</strong>
  <%= @asset.exchange_code %>
</p>
<p>
  <strong>Symbol:</strong>
  <%= @asset.symbol %>
</p>
<p>
  <strong>Asset Type:</strong>
  <%= @asset.asset_type_id %>
</p>
<p>
  <strong>Desc:</strong>
  <%= @asset.desc %>
</p>

<p>
  <%= link_to "Edit", edit_asset_path(@asset) %> |
  <%= link_to "Destroy", @asset, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", assets_path %>
</p>