config/routes.rb
Zmd::Application.routes.draw do
  resources :splits

  resources :technicals

  resources :fundamentals

  resources :exchanges

  resources :eod_prices

  resources :asset_types

  resources :assets

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  attr_accessible :exchange_code, :symbol, :asset_type_id, :desc
end

app/models/asset_type.rb
class AssetType < ActiveRecord::Base
  attr_accessible :short_name, :long_name
end

app/models/eod_price.rb
class EodPrice < ActiveRecord::Base
  attr_accessible :asset_id, :mark_date, :open_px, :high_px, :low_px, :close_px, :volume, :open_interest
end

app/models/exchange.rb
class Exchange < ActiveRecord::Base
  attr_accessible :code, :name, :load_issues
end

app/models/fundamentals.rb
class Fundamentals < ActiveRecord::Base
  attr_accessible :asset_id, :sector, :industry, :pe, :eps, :div_yield, :shares, :dps, :peg, :p2s, :p2b
end

app/models/split.rb
class Split < ActiveRecord::Base
  attr_accessible :asset_id, :cax_date, :terms
end

app/models/technicals.rb
class Technicals < ActiveRecord::Base
  attr_accessible :asset_id, :previous, :change, :volume_change, :Week_high, :Week_low, :Week_change, :avg_week_change, :avg_week_volume, :month_high, :month_low, :month-change, :avg_month-change, :avg_month_volume, :year_high, :year_low, :year_change, :avg_year_change, :avg_year_volume, :ma5, :ma20, :ma50, :ma100, :ma200, :rsi14, :sto9, :wpr14, :mtm14, :roc14, :ptc
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  def index
    @assets = Asset.all
  end
  
  def show
    @asset = Asset.find(params[:id])
  end
  
  def new
    @asset = Asset.new
  end
  
  def create
    @asset = Asset.new(params[:asset])
    if @asset.save
      flash[:notice] = "Successfully created asset."
      redirect_to @asset
    else
      render :action => 'new'
    end
  end
  
  def edit
    @asset = Asset.find(params[:id])
  end
  
  def update
    @asset = Asset.find(params[:id])
    if @asset.update_attributes(params[:asset])
      flash[:notice] = "Successfully updated asset."
      redirect_to @asset
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy
    flash[:notice] = "Successfully destroyed asset."
    redirect_to assets_url
  end
end

app/controllers/eod_prices_controller.rb
class EodPricesController < ApplicationController
  def index
    @eod_prices = EodPrice.all
  end
  
  def show
    @eod_price = EodPrice.find(params[:id])
  end
  
  def new
    @eod_price = EodPrice.new
  end
  
  def create
    @eod_price = EodPrice.new(params[:eod_price])
    if @eod_price.save
      flash[:notice] = "Successfully created eod price."
      redirect_to @eod_price
    else
      render :action => 'new'
    end
  end
  
  def edit
    @eod_price = EodPrice.find(params[:id])
  end
  
  def update
    @eod_price = EodPrice.find(params[:id])
    if @eod_price.update_attributes(params[:eod_price])
      flash[:notice] = "Successfully updated eod price."
      redirect_to @eod_price
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @eod_price = EodPrice.find(params[:id])
    @eod_price.destroy
    flash[:notice] = "Successfully destroyed eod price."
    redirect_to eod_prices_url
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  def index
    @exchanges = Exchange.all
  end
  
  def show
    @exchange = Exchange.find(params[:id])
  end
  
  def new
    @exchange = Exchange.new
  end
  
  def create
    @exchange = Exchange.new(params[:exchange])
    if @exchange.save
      flash[:notice] = "Successfully created exchange."
      redirect_to @exchange
    else
      render :action => 'new'
    end
  end
  
  def edit
    @exchange = Exchange.find(params[:id])
  end
  
  def update
    @exchange = Exchange.find(params[:id])
    if @exchange.update_attributes(params[:exchange])
      flash[:notice] = "Successfully updated exchange."
      redirect_to @exchange
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @exchange = Exchange.find(params[:id])
    @exchange.destroy
    flash[:notice] = "Successfully destroyed exchange."
    redirect_to exchanges_url
  end
end

app/controllers/splits_controller.rb
class SplitsController < ApplicationController
  def index
    @splits = Split.all
  end
  
  def show
    @split = Split.find(params[:id])
  end
  
  def new
    @split = Split.new
  end
  
  def create
    @split = Split.new(params[:split])
    if @split.save
      flash[:notice] = "Successfully created split."
      redirect_to @split
    else
      render :action => 'new'
    end
  end
  
  def edit
    @split = Split.find(params[:id])
  end
  
  def update
    @split = Split.find(params[:id])
    if @split.update_attributes(params[:split])
      flash[:notice] = "Successfully updated split."
      redirect_to @split
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @split = Split.find(params[:id])
    @split.destroy
    flash[:notice] = "Successfully destroyed split."
    redirect_to splits_url
  end
end

app/controllers/technicals_controller.rb
class TechnicalsController < ApplicationController
  def index
    @technicals = Technicals.all
  end
  
  def show
    @technicals = Technicals.find(params[:id])
  end
  
  def new
    @technicals = Technicals.new
  end
  
  def create
    @technicals = Technicals.new(params[:technicals])
    if @technicals.save
      flash[:notice] = "Successfully created technicals."
      redirect_to @technicals
    else
      render :action => 'new'
    end
  end
  
  def edit
    @technicals = Technicals.find(params[:id])
  end
  
  def update
    @technicals = Technicals.find(params[:id])
    if @technicals.update_attributes(params[:technicals])
      flash[:notice] = "Successfully updated technicals."
      redirect_to @technicals
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @technicals = Technicals.find(params[:id])
    @technicals.destroy
    flash[:notice] = "Successfully destroyed technicals."
    redirect_to technicals_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asset_types_helper.rb
module AssetTypesHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/eod_prices_helper.rb
module EodPricesHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/helpers/fundamentals_helper.rb
module FundamentalsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/splits_helper.rb
module SplitsHelper
end

app/helpers/technicals_helper.rb
module TechnicalsHelper
end

app/views/eod_prices/_form.html.erb
<%= form_for @eod_price do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :asset_id %><br />
    <%= f.text_field :asset_id %>
  </p>
  <p>
    <%= f.label :mark_date %><br />
    <%= f.datetime_select :mark_date %>
  </p>
  <p>
    <%= f.label :open_px %><br />
    <%= f.text_field :open_px %>
  </p>
  <p>
    <%= f.label :high_px %><br />
    <%= f.text_field :high_px %>
  </p>
  <p>
    <%= f.label :low_px %><br />
    <%= f.text_field :low_px %>
  </p>
  <p>
    <%= f.label :close_px %><br />
    <%= f.text_field :close_px %>
  </p>
  <p>
    <%= f.label :volume %><br />
    <%= f.text_field :volume %>
  </p>
  <p>
    <%= f.label :open_interest %><br />
    <%= f.text_field :open_interest %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/eod_prices/edit.html.erb
<% title "Edit Eod Price" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @eod_price %> |
  <%= link_to "View All", eod_prices_path %>
</p>

app/views/eod_prices/index.html.erb
<% title "Eod Prices" %>

<table>
  <tr>
    <th>Asset</th>
    <th>Mark Date</th>
    <th>Open Px</th>
    <th>High Px</th>
    <th>Low Px</th>
    <th>Close Px</th>
    <th>Volume</th>
    <th>Open Interest</th>
  </tr>
  <% for eod_price in @eod_prices %>
    <tr>
      <td><%= eod_price.asset_id %></td>
      <td><%= eod_price.mark_date %></td>
      <td><%= eod_price.open_px %></td>
      <td><%= eod_price.high_px %></td>
      <td><%= eod_price.low_px %></td>
      <td><%= eod_price.close_px %></td>
      <td><%= eod_price.volume %></td>
      <td><%= eod_price.open_interest %></td>
      <td><%= link_to "Show", eod_price %></td>
      <td><%= link_to "Edit", edit_eod_price_path(eod_price) %></td>
      <td><%= link_to "Destroy", eod_price, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Eod Price", new_eod_price_path %></p>

app/views/eod_prices/new.html.erb
<% title "New Eod Price" %>

<%= render 'form' %>

<p><%= link_to "Back to List", eod_prices_path %></p>

app/views/eod_prices/show.html.erb
<% title "Eod Price" %>

<p>
  <strong>Asset:</strong>
  <%= @eod_price.asset_id %>
</p>
<p>
  <strong>Mark Date:</strong>
  <%= @eod_price.mark_date %>
</p>
<p>
  <strong>Open Px:</strong>
  <%= @eod_price.open_px %>
</p>
<p>
  <strong>High Px:</strong>
  <%= @eod_price.high_px %>
</p>
<p>
  <strong>Low Px:</strong>
  <%= @eod_price.low_px %>
</p>
<p>
  <strong>Close Px:</strong>
  <%= @eod_price.close_px %>
</p>
<p>
  <strong>Volume:</strong>
  <%= @eod_price.volume %>
</p>
<p>
  <strong>Open Interest:</strong>
  <%= @eod_price.open_interest %>
</p>

<p>
  <%= link_to "Edit", edit_eod_price_path(@eod_price) %> |
  <%= link_to "Destroy", @eod_price, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", eod_prices_path %>
</p>

app/views/exchanges/_form.html.erb
<%= form_for @exchange do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :load_issues %><br />
    <%= f.check_box :load_issues %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/exchanges/edit.html.erb
<% title "Edit Exchange" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @exchange %> |
  <%= link_to "View All", exchanges_path %>
</p>

app/views/exchanges/index.html.erb
<% title "Exchanges" %>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th>Load Issues</th>
  </tr>
  <% for exchange in @exchanges %>
    <tr>
      <td><%= exchange.code %></td>
      <td><%= exchange.name %></td>
      <td><%= exchange.load_issues %></td>
      <td><%= link_to "Show", exchange %></td>
      <td><%= link_to "Edit", edit_exchange_path(exchange) %></td>
      <td><%= link_to "Destroy", exchange, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Exchange", new_exchange_path %></p>

app/views/exchanges/new.html.erb
<% title "New Exchange" %>

<%= render 'form' %>

<p><%= link_to "Back to List", exchanges_path %></p>

app/views/exchanges/show.html.erb
<% title "Exchange" %>

<p>
  <strong>Code:</strong>
  <%= @exchange.code %>
</p>
<p>
  <strong>Name:</strong>
  <%= @exchange.name %>
</p>
<p>
  <strong>Load Issues:</strong>
  <%= @exchange.load_issues %>
</p>

<p>
  <%= link_to "Edit", edit_exchange_path(@exchange) %> |
  <%= link_to "Destroy", @exchange, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", exchanges_path %>
</p>

app/views/splits/_form.html.erb
<%= form_for @split do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :asset_id %><br />
    <%= f.text_field :asset_id %>
  </p>
  <p>
    <%= f.label :cax_date %><br />
    <%= f.datetime_select :cax_date %>
  </p>
  <p>
    <%= f.label :terms %><br />
    <%= f.text_field :terms %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/splits/edit.html.erb
<% title "Edit Split" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @split %> |
  <%= link_to "View All", splits_path %>
</p>

app/views/splits/index.html.erb
<% title "Splits" %>

<table>
  <tr>
    <th>Asset</th>
    <th>Cax Date</th>
    <th>Terms</th>
  </tr>
  <% for split in @splits %>
    <tr>
      <td><%= split.asset_id %></td>
      <td><%= split.cax_date %></td>
      <td><%= split.terms %></td>
      <td><%= link_to "Show", split %></td>
      <td><%= link_to "Edit", edit_split_path(split) %></td>
      <td><%= link_to "Destroy", split, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Split", new_split_path %></p>

app/views/splits/new.html.erb
<% title "New Split" %>

<%= render 'form' %>

<p><%= link_to "Back to List", splits_path %></p>

app/views/splits/show.html.erb
<% title "Split" %>

<p>
  <strong>Asset:</strong>
  <%= @split.asset_id %>
</p>
<p>
  <strong>Cax Date:</strong>
  <%= @split.cax_date %>
</p>
<p>
  <strong>Terms:</strong>
  <%= @split.terms %>
</p>

<p>
  <%= link_to "Edit", edit_split_path(@split) %> |
  <%= link_to "Destroy", @split, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", splits_path %>
</p>

app/views/technicals/_form.html.erb
<%= form_for @technicals do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :asset_id %><br />
    <%= f.text_field :asset_id %>
  </p>
  <p>
    <%= f.label :previous %><br />
    <%= f.text_field :previous %>
  </p>
  <p>
    <%= f.label :change %><br />
    <%= f.text_field :change %>
  </p>
  <p>
    <%= f.label :volume_change %><br />
    <%= f.text_field :volume_change %>
  </p>
  <p>
    <%= f.label :Week_high %><br />
    <%= f.text_field :Week_high %>
  </p>
  <p>
    <%= f.label :Week_low %><br />
    <%= f.text_field :Week_low %>
  </p>
  <p>
    <%= f.label :Week_change %><br />
    <%= f.text_field :Week_change %>
  </p>
  <p>
    <%= f.label :avg_week_change %><br />
    <%= f.text_field :avg_week_change %>
  </p>
  <p>
    <%= f.label :avg_week_volume %><br />
    <%= f.text_field :avg_week_volume %>
  </p>
  <p>
    <%= f.label :month_high %><br />
    <%= f.text_field :month_high %>
  </p>
  <p>
    <%= f.label :month_low %><br />
    <%= f.text_field :month_low %>
  </p>
  <p>
    <%= f.label :month-change %><br />
    <%= f.text_field :month-change %>
  </p>
  <p>
    <%= f.label :avg_month-change %><br />
    <%= f.text_field :avg_month-change %>
  </p>
  <p>
    <%= f.label :avg_month_volume %><br />
    <%= f.text_field :avg_month_volume %>
  </p>
  <p>
    <%= f.label :year_high %><br />
    <%= f.text_field :year_high %>
  </p>
  <p>
    <%= f.label :year_low %><br />
    <%= f.text_field :year_low %>
  </p>
  <p>
    <%= f.label :year_change %><br />
    <%= f.text_field :year_change %>
  </p>
  <p>
    <%= f.label :avg_year_change %><br />
    <%= f.text_field :avg_year_change %>
  </p>
  <p>
    <%= f.label :avg_year_volume %><br />
    <%= f.text_field :avg_year_volume %>
  </p>
  <p>
    <%= f.label :ma5 %><br />
    <%= f.text_field :ma5 %>
  </p>
  <p>
    <%= f.label :ma20 %><br />
    <%= f.text_field :ma20 %>
  </p>
  <p>
    <%= f.label :ma50 %><br />
    <%= f.text_field :ma50 %>
  </p>
  <p>
    <%= f.label :ma100 %><br />
    <%= f.text_field :ma100 %>
  </p>
  <p>
    <%= f.label :ma200 %><br />
    <%= f.text_field :ma200 %>
  </p>
  <p>
    <%= f.label :rsi14 %><br />
    <%= f.text_field :rsi14 %>
  </p>
  <p>
    <%= f.label :sto9 %><br />
    <%= f.text_field :sto9 %>
  </p>
  <p>
    <%= f.label :wpr14 %><br />
    <%= f.text_field :wpr14 %>
  </p>
  <p>
    <%= f.label :mtm14 %><br />
    <%= f.text_field :mtm14 %>
  </p>
  <p>
    <%= f.label :roc14 %><br />
    <%= f.text_field :roc14 %>
  </p>
  <p>
    <%= f.label :ptc %><br />
    <%= f.text_field :ptc %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/technicals/edit.html.erb
<% title "Edit Technicals" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @technicals %> |
  <%= link_to "View All", technicals_path %>
</p>

app/views/technicals/index.html.erb
<% title "Technicals" %>

<table>
  <tr>
    <th>Asset</th>
    <th>Previous</th>
    <th>Change</th>
    <th>Volume Change</th>
    <th>Week High</th>
    <th>Week Low</th>
    <th>Week Change</th>
    <th>Avg Week Change</th>
    <th>Avg Week Volume</th>
    <th>Month High</th>
    <th>Month Low</th>
    <th>Month Change</th>
    <th>Avg Month Change</th>
    <th>Avg Month Volume</th>
    <th>Year High</th>
    <th>Year Low</th>
    <th>Year Change</th>
    <th>Avg Year Change</th>
    <th>Avg Year Volume</th>
    <th>Ma5</th>
    <th>Ma20</th>
    <th>Ma50</th>
    <th>Ma100</th>
    <th>Ma200</th>
    <th>Rsi14</th>
    <th>Sto9</th>
    <th>Wpr14</th>
    <th>Mtm14</th>
    <th>Roc14</th>
    <th>Ptc</th>
  </tr>
  <% for technicals in @technicals %>
    <tr>
      <td><%= technicals.asset_id %></td>
      <td><%= technicals.previous %></td>
      <td><%= technicals.change %></td>
      <td><%= technicals.volume_change %></td>
      <td><%= technicals.Week_high %></td>
      <td><%= technicals.Week_low %></td>
      <td><%= technicals.Week_change %></td>
      <td><%= technicals.avg_week_change %></td>
      <td><%= technicals.avg_week_volume %></td>
      <td><%= technicals.month_high %></td>
      <td><%= technicals.month_low %></td>
      <td><%= technicals.month-change %></td>
      <td><%= technicals.avg_month-change %></td>
      <td><%= technicals.avg_month_volume %></td>
      <td><%= technicals.year_high %></td>
      <td><%= technicals.year_low %></td>
      <td><%= technicals.year_change %></td>
      <td><%= technicals.avg_year_change %></td>
      <td><%= technicals.avg_year_volume %></td>
      <td><%= technicals.ma5 %></td>
      <td><%= technicals.ma20 %></td>
      <td><%= technicals.ma50 %></td>
      <td><%= technicals.ma100 %></td>
      <td><%= technicals.ma200 %></td>
      <td><%= technicals.rsi14 %></td>
      <td><%= technicals.sto9 %></td>
      <td><%= technicals.wpr14 %></td>
      <td><%= technicals.mtm14 %></td>
      <td><%= technicals.roc14 %></td>
      <td><%= technicals.ptc %></td>
      <td><%= link_to "Show", technicals %></td>
      <td><%= link_to "Edit", edit_technicals_path(technicals) %></td>
      <td><%= link_to "Destroy", technicals, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Technicals", new_technicals_path %></p>

app/views/technicals/new.html.erb
<% title "New Technicals" %>

<%= render 'form' %>

<p><%= link_to "Back to List", technicals_path %></p>

app/views/technicals/show.html.erb
<% title "Technicals" %>

<p>
  <strong>Asset:</strong>
  <%= @technicals.asset_id %>
</p>
<p>
  <strong>Previous:</strong>
  <%= @technicals.previous %>
</p>
<p>
  <strong>Change:</strong>
  <%= @technicals.change %>
</p>
<p>
  <strong>Volume Change:</strong>
  <%= @technicals.volume_change %>
</p>
<p>
  <strong>Week High:</strong>
  <%= @technicals.Week_high %>
</p>
<p>
  <strong>Week Low:</strong>
  <%= @technicals.Week_low %>
</p>
<p>
  <strong>Week Change:</strong>
  <%= @technicals.Week_change %>
</p>
<p>
  <strong>Avg Week Change:</strong>
  <%= @technicals.avg_week_change %>
</p>
<p>
  <strong>Avg Week Volume:</strong>
  <%= @technicals.avg_week_volume %>
</p>
<p>
  <strong>Month High:</strong>
  <%= @technicals.month_high %>
</p>
<p>
  <strong>Month Low:</strong>
  <%= @technicals.month_low %>
</p>
<p>
  <strong>Month Change:</strong>
  <%= @technicals.month-change %>
</p>
<p>
  <strong>Avg Month Change:</strong>
  <%= @technicals.avg_month-change %>
</p>
<p>
  <strong>Avg Month Volume:</strong>
  <%= @technicals.avg_month_volume %>
</p>
<p>
  <strong>Year High:</strong>
  <%= @technicals.year_high %>
</p>
<p>
  <strong>Year Low:</strong>
  <%= @technicals.year_low %>
</p>
<p>
  <strong>Year Change:</strong>
  <%= @technicals.year_change %>
</p>
<p>
  <strong>Avg Year Change:</strong>
  <%= @technicals.avg_year_change %>
</p>
<p>
  <strong>Avg Year Volume:</strong>
  <%= @technicals.avg_year_volume %>
</p>
<p>
  <strong>Ma5:</strong>
  <%= @technicals.ma5 %>
</p>
<p>
  <strong>Ma20:</strong>
  <%= @technicals.ma20 %>
</p>
<p>
  <strong>Ma50:</strong>
  <%= @technicals.ma50 %>
</p>
<p>
  <strong>Ma100:</strong>
  <%= @technicals.ma100 %>
</p>
<p>
  <strong>Ma200:</strong>
  <%= @technicals.ma200 %>
</p>
<p>
  <strong>Rsi14:</strong>
  <%= @technicals.rsi14 %>
</p>
<p>
  <strong>Sto9:</strong>
  <%= @technicals.sto9 %>
</p>
<p>
  <strong>Wpr14:</strong>
  <%= @technicals.wpr14 %>
</p>
<p>
  <strong>Mtm14:</strong>
  <%= @technicals.mtm14 %>
</p>
<p>
  <strong>Roc14:</strong>
  <%= @technicals.roc14 %>
</p>
<p>
  <strong>Ptc:</strong>
  <%= @technicals.ptc %>
</p>

<p>
  <%= link_to "Edit", edit_technicals_path(@technicals) %> |
  <%= link_to "Destroy", @technicals, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", technicals_path %>
</p>